#!/bin/bash


cp /mnt/minerva1/nlp/projects/naki_cpk/xprext00/wiwkistatstest/wikipedia_statistics_2016-08.tsv wiki_stats

python2 wiki_stats_to_KB.py > KBstats.all
python2 metrics_to_KB.py -k KBstats.all | sed '/^\s*$/d' > KBstatsMetrics.all


echo -n "VERSION=" | cat - VERSION HEAD-KB KBstatsMetrics.all > KB-HEAD.all

#rm KBstats.all wiki_stats
